const fruits = ["apple", "banana", "orange", " grape", "kiwi"];
console.log(fruits);
console.log("Lenght of fruits: " + fruits.length);
console.log("Element at Index 2: " + fruits[2]);
console.log("Last Element of Fruits: " + fruits.slice(-1));
const vegetables = [];
vegetables.push(prompt("add vegetable 1"));
vegetables.push(prompt("add vegetable 2"));
vegetables.push(prompt("add vegetable 3"));
console.log(vegetables);
console.log("Lenght of vegetables: " + vegetables.length);
